# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f662fbce22cd0c54f12444bc1c4c4daaaa4857728821e0665cb8df6b3d8df70ebc85f65deffb442e8fc45462c7e771e16ef39cc85d9a01a42968469990f90b93

test:
  secret_key_base: 3f56b9d3589f22f2815b2e33e628855b74509a78b4d419845c2f6a31c454e83bb920bdfacd4c8ecff5a8634b8e9a518094dbcbf245df40c0c501fbb028c6f703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
